def p(t,v,k,w=4,c='o',**kw): return dict(t=t,v=v,k=k,w=int(w),c=c,**kw)
PAGES=[
 dict(id='home',t='Command Center',ic='◈'),
 dict(id='rev',t='Revenue & ARPU',ic='৳',sub='Service revenue across voice, data, SMS and VAS',
  kpis=[['rev','Service revenue','৳'],['arpu','ARPU / month','৳'],['ltv','LTV (35% margin assumed)','৳'],['ltvcac','LTV : CAC','','x']],
  panels=[p('Monthly service revenue (৳ M)','col','revM',6,'y',tb='usage',g='M',m='rev'),p('ARPU trend (৳)','line','arpuM',6,tb='usage',g='M',m='arpu'),
   p('Revenue mix','mixd','mix',tb='usage',parts=[['Data','dr'],['Voice','vr'],['SMS','sr'],['VAS','vs']]),
   p('ARPU by network tech (৳)','bars','arpuTech',4,'r',tb='usage',g='Network',m='arpu'),p('Revenue by division (৳ M)','bars','revDiv',tb='usage',g='Division',m='rev')]),
 dict(id='sub',t='Subscribers & Churn',ic='👥',sub='Acquisition, retention and churn drivers',
  kpis=[['subs','Subscribers'],['active','Active'],['churn','Churn rate','','%'],['mch','Monthly churn','','%']],
  panels=[p('Gross adds vs churned','dual','gaCh',6,tb='ev',g='M',m='ga',m2='chm'),p('Net adds','col','netM',6,'y',tb='ev',g='M',m='net'),
   p('Churn type','donut','churnType',tb='ev',g='ChurnType',m='chm'),p('Churn by division %','bars','churnDiv',4,'r',tb='cust',g='Division',m='churn'),
   p('Churn by network %','bars','churnNet',tb='cust',g='Network',m='churn'),p('Churn by ticket issue %','bars','churnIssue',6,'r',tb='tick',g='Issue',m='chtk'),
   p('OTT effect on churn %','bars','ottChurn',6,tb='cust',g='OTT',m='churn')]),
 dict(id='net',t='Network Performance',ic='📡',sub='Quality, capacity and outage KPIs by division',
  kpis=[['drop','Call drop','','%'],['cssr','CSSR','','%'],['thr','Throughput','','Mbps'],['avail','Availability','','%'],['mttr','MTTR','','min']],
  panels=[p('Call drop heatmap: division x month (%)','heat','dropHeat',12),p('Call drop trend (%)','line','dropM',6,'r',tb='net',g='M',m='drop'),
   p('Outages per month','col','outM',6,tb='out',g='M',m='ocount'),p('Outage causes','donut','outCause',tb='out',g='Cause',m='ocount'),
   p('MTTR by cause (min)','bars','mttrCause',tb='out',g='Cause',m='mttr'),p('Most congested sites (PRB %)','bars','congest',4,'r',tb='site',g='Site',m='prb',top=8),
   p('Throughput by area (Mbps)','bars','thrArea',6,'y',tb='net',g='Area',m='thr'),p('Availability by division %','bars','availDiv',6,tb='net',g='Division',m='avail')]),
 dict(id='cx',t='Customer Experience',ic='☎',sub='Satisfaction, support quality and SLA',
  kpis=[['nps','NPS'],['csat','CSAT (1-5)'],['fcr','First-contact resolution','','%'],['sla','SLA met','','%']],
  panels=[p('Tickets per month','col','ticketM',6,tb='tick',g='M',m='tix'),p('NPS mix','mixd','npsMix',3,tb='cust',parts=[['Promoters','pro'],['Passives','pas'],['Detractors','det']]),
   p('Ticket channels','donut','ticketCh',3,tb='tick',g='TChan',m='tix'),p('CSAT by issue','bars','csatIssue',4,'y',tb='tick',g='Issue',m='csat'),
   p('FCR % by channel','bars','fcrCh',tb='tick',g='TChan',m='fcr'),p('SLA % by issue','bars','slaIssue',4,'r',tb='tick',g='Issue',m='sla'),
   p('Resolution time (min)','bars','resIssue',12,tb='tick',g='Issue',m='res')]),
 dict(id='use',t='Usage & Digital',ic='📶',sub='Data, voice and OTT engagement',
  kpis=[['mou','Voice min / sub'],['dgb','Data GB / sub'],['tb','Streamed','','TB'],['ad','OTT ad spend','৳']],
  panels=[p('Data per subscriber (GB)','line','dataM',6,'y',tb='usage',g='M',m='dgb'),p('Voice minutes per subscriber','line','mouM',6,tb='usage',g='M',m='mou'),
   p('Network mix','donut','netMix',tb='cust',g='Network',m='subs'),p('Streaming by platform (GB)','bars','platGB',tb='stream',g='Platform',m='gb'),
   p('Ad spend per GB (৳)','bars','adGB',4,'r',tb='stream',g='Platform',m='adgb'),p('Monthly streaming (GB)','col','streamM',12,tb='stream',g='M',m='gb')]),
 dict(id='bill',t='Billing & Collections',ic='🧾',sub='Postpaid invoicing, collections and bad debt',
  kpis=[['collect','Collection efficiency','','%'],['bad','Bad debt','','%'],['overdue','Overdue','৳'],['billed','Billed','৳']],
  panels=[p('Collection efficiency (%)','line','collectM',6,'y',tb='bill',g='M',m='coll'),p('Overdue aging (৳ M)','col','aging',6,'r',tb='bill',g='Aging',m='unp',skip='Paid'),
   p('Collection gauge','gauge','collect'),p('Bad debt % by division','bars','badDiv',4,'r',tb='bill',g='Division',m='bad'),p('Collection % by division','bars','collDiv',tb='bill',g='Division',m='coll')]),
 dict(id='mkt',t='Sales & Distribution',ic='🎯',sub='Campaign efficiency, channels and distributors',
  kpis=[['cac','CAC','৳'],['roi','Campaign ROI','','x'],['ltvcac','LTV : CAC','','x']],
  panels=[p('Campaign spend (৳ M)','col','campM',6,tb='camp',g='M',m='spend'),p('Acquisition channels','donut','acq',3,tb='ev',g='Acq',m='ga'),
   p('Top-up by distributor tier','donut','tier',3,tb='rech',g='Tier',m='amt'),p('CAC by channel (৳)','bars','cacCh',4,'r',tb='camp',g='CChan',m='cac'),
   p('ROI by channel (x)','bars','roiCh',tb='camp',g='CChan',m='roi'),p('Top distributors (৳ K)','bars','topDist',4,'y',tb='rechd',g='Dist',m='amtk',top=8)]),
 dict(id='hr',t='Workforce',ic='🧑',sub='Agent productivity, retention and distribution',
  kpis=[['hc','Headcount'],['turn','Turnover','','%'],['perf','Avg rating'],['tpa','Tickets / agent']],
  panels=[p('Resolution by dept (min)','bars','deptRes',tb='tickd',g='Dept',m='res'),p('CSAT by dept','bars','deptCsat',4,'y',tb='tickd',g='Dept',m='csat'),
   p('Turnover % by dept','bars','deptTurn',4,'r',tb='emp',g='Dept',m='turn'),p('Performance mix','donut','perfMix',tb='emp',g='Rating',m='hc'),
   p('Headcount by division','bars','hcDiv',tb='emp',g='Division',m='hc'),p('Avg salary by dept (৳ K)','bars','salDept',4,'y',tb='emp',g='Dept',m='sal')]),
]
FIELDS={'revM':'Dim_Date[MonthName] | [Service Revenue]','arpuM':'Dim_Date[MonthName] | [ARPU]','mix':'_Mix[Service] | [Mix Value]',
'arpuTech':'Dim_Customers[Network] | [ARPU]','revDiv':'Dim_Division[Division] | [Service Revenue]','gaCh':'Dim_Date[MonthName] | [Gross Adds], [Churned (by date)]',
'netM':'Dim_Date[MonthName] | [Net Adds]','churnType':'Fact_Subscriptions[ChurnType] | [Churned Subscribers]','churnDiv':'Dim_Division[Division] | [Churn Rate %]',
'churnNet':'Dim_Customers[Network] | [Churn Rate %]','churnIssue':'Fact_Network_Service_Calls[IssueCategory] | [Ticket Churn Rate %]','ottChurn':'Dim_Customers[OTT User] | [Churn Rate %]',
'dropHeat':'Dim_Division[Division] x Dim_Date[MonthName] | [Call Drop Rate %]','dropM':'Dim_Date[MonthName] | [Call Drop Rate %]','outM':'Dim_Date[MonthName] | [Outage Count]',
'outCause':'Fact_Network_Outages[Cause] | [Outage Count]','mttrCause':'Fact_Network_Outages[Cause] | [MTTR min]','congest':'Dim_Towers[SiteID] | [Avg PRB Utilization] (Top N 8)',
'thrArea':'Dim_Towers[Area] | [Avg Throughput Mbps]','availDiv':'Dim_Division[Division] | [Site Availability %]','ticketM':'Dim_Date[MonthName] | [Ticket Count]',
'npsMix':'_NPS[Group] | [NPS Group Count]','ticketCh':'Fact_Network_Service_Calls[TicketChannel] | [Ticket Count]','csatIssue':'Fact_Network_Service_Calls[IssueCategory] | [Avg CSAT]',
'fcrCh':'Fact_Network_Service_Calls[TicketChannel] | [FCR %]','slaIssue':'Fact_Network_Service_Calls[IssueCategory] | [SLA Compliance %]','resIssue':'Fact_Network_Service_Calls[IssueCategory] | [Avg Ticket Resolution]',
'dataM':'Dim_Date[MonthName] | [Data per Sub GB]','mouM':'Dim_Date[MonthName] | [MOU]','netMix':'Dim_Customers[Network] | [Total Subscribers]',
'platGB':'Fact_Digital_Streaming_VAS[Platform] | [Streaming GB]','adGB':'Fact_Digital_Streaming_VAS[Platform] | [Ad Cost per GB]','streamM':'Dim_Date[MonthName] | [Streaming GB]',
'collectM':'Dim_Date[MonthName] | [Collection Efficiency %]','aging':'Fact_Billing[Aging Bucket] | [Overdue Amount] (filter out Paid)','collect':'Value [Collection Efficiency %], Minimum 0, Maximum 1, Target 0.95',
'badDiv':'Dim_Division[Division] | [Bad Debt %]','collDiv':'Dim_Division[Division] | [Collection Efficiency %]','campM':'Dim_Date[MonthName] | [Campaign Spend]',
'acq':'Fact_Subscriptions[AcquisitionChannel] | [Gross Adds]','tier':'Dim_Distributors[Tier] | [Recharge Sales]','cacCh':'Fact_Marketing_Campaigns[Channel] | [Campaign CAC]',
'roiCh':'Fact_Marketing_Campaigns[Channel] | [Campaign ROI]','topDist':'Dim_Distributors[Name] | [Recharge Sales] (Top N 8)','deptRes':'Dim_Employees_HR[Department] | [Avg Ticket Resolution]',
'deptCsat':'Dim_Employees_HR[Department] | [Avg CSAT]','deptTurn':'Dim_Employees_HR[Department] | [Employee Turnover %]','perfMix':'Dim_Employees_HR[PerformanceRating] | [Headcount]',
'hcDiv':'Dim_Division[Division] | [Headcount]','salDept':'Dim_Employees_HR[Department] | [Avg Salary]'}
